### PR TITLE
First exercise sheet

### PR DESCRIPTION
**Pull request by exot**
- don't use directories for versioning; use tags and ‘git show’ instead
- adding first exercise sheet and corresponding LaTeX documents

### CODE REVIEW

**Comment by mkroetzsch** [comment]
This change is now in conflict. There are pros and cons regarding the use of directories. If you view it as one project that evolves over time, then tags are nice. If you consider this as separate projects for each term, then it makes sense to retain the final state rather than to overwrite it. We can try tags/releases, but we must not forget to actually release at the end of the seminar.

**Comment by exot** [comment]
As far as I know, releases on github are just (fancy ways of showing) tags.  Moreover, tagging can also be done later on, so even if we forget to "release" after the semester, we can place the corresponding tag at any later point in time.

I will fix the merge conflict soon.

**Comment by mkroetzsch** [comment]
Yes, a github release is a kind of tag++ that gets some additional prominence and descriptions on the web site, making it a bit more convenient to find and access.

**Comment by exot** [comment]
Conflict is fixed, feel free to merge and close this comment.

**Pull request merged**
